### ISSUE TITLE
Fix README.md: pomodone-ubuntu-2004

### ISSUE THREAD

**Issue by colematt** [jcfergus/fixed-it-for-me#1]
Currently has the following instructions:
```
wget http://mirrors.kernel.org/ubuntu/pool/main/p/pango1.0/libpango-1.0-0_1.42.4-7_amd64.deb
wget http://mirrors.kernel.org/ubuntu/pool/main/p/pango1.0/libpangocairo-1.0-0_1.42.4-7_amd64.deb
wget http://mirrors.kernel.org/ubuntu/pool/main/p/pango1.0/libpangoft2-1.0-0_1.42.4-7_amd64.deb
cd /opt/PomoDoneApp
sudo dpkg -x libpango-1.0-0_1.42.4-7_amd64.deb .
sudo dpkg -x libpangocairo-1.0-0_1.42.4-7_amd64.deb
sudo dpkg -x libpangoft2-1.0-0_1.42.4-7_amd64.deb
LD_LIBRARY_PATH=/opt/PomoDoneApp/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH ./pomodoneapp
```

But this will cause the following errors on lines 6-7:
```
dpkg-deb: error: --extract needs a target directory.
Perhaps you should be using dpkg --install ?

Type dpkg-deb --help for help about manipulating *.deb files;
Type dpkg --help for help about installing and deinstalling packages.
```

Fixed those lines with the following instructions instead:
```
sudo dpkg -x libpangocairo-1.0-0_1.42.4-7_amd64.deb .
sudo dpkg -x libpangoft2-1.0-0_1.42.4-7_amd64.deb .
```

Other than that, the instructions worked, and got my Pomodoneapp running again. Thanks for fixing this!

**Comment by sonuishaq67** [comment]
LD_LIBRARY_PATH=/opt/PomoDoneApp/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH ./pomodoneapp when I run this in /opt/PomoDoneApp it works but when I try to click on the icon it's the same as before ,I use Gnome if that helps .I tried changing the exec value in .desktop file of pomodoneapp but I don't think i got the right one can you help me by fixing the command to be executed in exec:

**Comment by jcfergus** [comment]
Good catch!  Sorry I just saw this!  Will fix shortly.
