### ISSUE TITLE
runs from terminal but not Desktop

### ISSUE THREAD

**Issue by sonuishaq67** [jcfergus/fixed-it-for-me#3]
LD_LIBRARY_PATH=/opt/PomoDoneApp/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH ./pomodoneapp when I run this in /opt/PomoDoneApp it works but when I try to click on the icon it's the same as before ,I use Gnome if that helps .I tried changing the exec value in .desktop file of pomodoneapp but I don't think i got the right one can you help me by fixing the command to be executed in exec:

**Comment by jcfergus** [comment]
Sorry, I'm just seeing this, @sonuishaq67 - it's been a bit since I looked at the .desktop file format, but my hunch would be something like 
```
Exec="LD_LIBRARY_PATH\=/opt/PomoDoneApp/usr/lib/x86_64-linux-gnu:\$LD_LIBRARY_PATH /opt/PomoDoneApp/pomodoneapp" %U
```
might be the ticket.

**Comment by sonuishaq67** [comment]
Thanks I'll check it out
