### ISSUE TITLE
Thanks for the PomoDoneApp tips

### ISSUE THREAD

**Issue by CaptainPackers** [jcfergus/fixed-it-for-me#7]
I could never get the /usr/share/applications/pomodoneapp.desktop to launch the app. I had to resort to writing a bash script in /opt/PomoDoneApp called pomodone that looks like this:

```
#!/bin/bash
export LD_LIBRARY_PATH=/opt/PomoDoneApp/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH
nohup /opt/PomoDoneApp/pomodoneapp > /dev/null 2>&1 &
```
Then I just created a symbolic link to my Desktop directory to make launching convenient.

I tried a lot of different things in the Exec line of the .desktop file, including

```
Exec=bash -c "export LD_LIBRARY_PATH=/opt/PomoDoneApp/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH; /opt/PomoDoneApp/pomodoneapp" %k
```
which I saw posted on [reddit](https://www.reddit.com/r/linux4noobs/comments/jhpxm1/pomodoneapp_ver_151545_wont_install_in_ubuntu_lts/?utm_source=share&utm_medium=web2x&context=3), but as I said, I could never get the app to launch using the .desktop method.

What amazes me the most about this is that Pomodone hasn't fixed their app distribution. I sent them an email and they just referred me to some of the hacks that have been posted on the internet.

Thanks again for sharing this. I really like PomoDone. I think it's one of the most flexible pomodoro timers available. Pomatez is a close second, but it lacks a few features that are available in Pomodone.

CaptainPackers

**Comment by jcfergus** [comment]
Thanks for the note - when I emailed with the team at Pomodone around the time I originally posted this, they mentioned that it was actually an issue in an upstream dependency that was going to take significant effort to update.  I haven't tracked where they've gone since then.
